/* AUTOGENERATED FILE. DO NOT EDIT. */
#include "unity.h"
#include <setjmp.h>
#include <stdio.h>

char MessageBuffer[50];

extern void setUp(void);
extern void tearDown(void);

extern void test_IgnoredTest(void);
extern void test_AnotherIgnoredTest(void);
extern void test_ThisFunctionHasNotBeenTested_NeedsToBeImplemented(void);

void resetTest(void);
void resetTest(void)
{
  tearDown();
  setUp();
}


int main(void)
{
  UnityBegin("test/TestProductionCode2.c");

  RUN_TEST(test_IgnoredTest, 13);
  RUN_TEST(test_AnotherIgnoredTest, 18);
  RUN_TEST(test_ThisFunctionHasNotBeenTested_NeedsToBeImplemented, 23);

  UnityEnd();
  return 0;
}
