/* AUTOGENERATED FILE. DO NOT EDIT. */
#include "unity.h"
#include <setjmp.h>
#include <stdio.h>

char MessageBuffer[50];

extern void setUp(void);
extern void tearDown(void);

extern void test_TheFirstThingToTest(void);
extern void test_TheSecondThingToTest(void);

static int suite_setup(void)
{
a_custom_setup();
}
static int suite_teardown(int num_failures)
{
a_custom_teardown();
}
static void runTest(UnityTestFunction test)
{
  if (TEST_PROTECT())
  {
      setUp();
      test();
  }
  if (TEST_PROTECT() && !TEST_IS_IGNORED)
  {
    tearDown();
  }
}
void resetTest()
{
  tearDown();
  setUp();
}


int main(void)
{
  suite_setup();
  Unity.TestFile = "test/testdata/testsample.c";
  UnityBegin();

  // RUN_TEST calls runTest
  RUN_TEST(test_TheFirstThingToTest, 21);
  RUN_TEST(test_TheSecondThingToTest, 43);

  return suite_teardown(UnityEnd());
}
