/* AUTOGENERATED FILE. DO NOT EDIT. */
#include "unity.h"
#include "one.h"
#include "two.h"
#include <setjmp.h>
#include <stdio.h>
#include "CException.h"

char MessageBuffer[50];
int GlobalExpectCount;
int GlobalVerifyOrder;
char* GlobalOrderError;

extern void setUp(void);
extern void tearDown(void);

extern void test_TheFirstThingToTest(void);
extern void test_TheSecondThingToTest(void);

static void runTest(UnityTestFunction test)
{
  if (TEST_PROTECT())
  {
    CEXCEPTION_T e;
    Try {
      setUp();
      test();
    } Catch(e) { TEST_ASSERT_EQUAL_HEX32_MESSAGE(CEXCEPTION_NONE, e, "Unhandled Exception!"); }
  }
  if (TEST_PROTECT() && !TEST_IS_IGNORED)
  {
    tearDown();
  }
}
void resetTest()
{
  tearDown();
  setUp();
}


int main(void)
{
  Unity.TestFile = "test/testdata/testsample.c";
  UnityBegin();

  // RUN_TEST calls runTest
  RUN_TEST(test_TheFirstThingToTest, 21);
  RUN_TEST(test_TheSecondThingToTest, 43);

  return (UnityEnd());
}
