/* AUTOGENERATED FILE. DO NOT EDIT. */
#include "unity.h"
#include "cmock.h"
#include <setjmp.h>
#include <stdio.h>
#include "Mockstanky.h"

char MessageBuffer[50];

extern void setUp(void);
extern void tearDown(void);

extern void test_TheFirstThingToTest(void);
extern void test_TheSecondThingToTest(void);

static void CMock_Init(void)
{
  Mockstanky_Init();
}
static void CMock_Verify(void)
{
  Mockstanky_Verify();
}
static void CMock_Destroy(void)
{
  Mockstanky_Destroy();
}
static int suite_setup(void)
{
a_custom_setup();
}
static int suite_teardown(int num_failures)
{
a_custom_teardown();
}
static void runTest(UnityTestFunction test)
{
  if (TEST_PROTECT())
  {
      CMock_Init();
      setUp();
      test();
      CMock_Verify();
  }
  CMock_Destroy();
  if (TEST_PROTECT() && !TEST_IS_IGNORED)
  {
    tearDown();
  }
}
void resetTest()
{
  CMock_Verify();
  CMock_Destroy();
  tearDown();
  CMock_Init();
  setUp();
}


int main(void)
{
  suite_setup();
  Unity.TestFile = "test/testdata/mocksample.c";
  UnityBegin();

  // RUN_TEST calls runTest
  RUN_TEST(test_TheFirstThingToTest, 21);
  RUN_TEST(test_TheSecondThingToTest, 43);

  return suite_teardown(UnityEnd());
}
