/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef __B_U_I_L_D__T_E_S_T_S_A_M_P_L_E___H_E_A_D_1__H_
#define __B_U_I_L_D__T_E_S_T_S_A_M_P_L_E___H_E_A_D_1__H_

#include "funky.h"
#include "stanky.h"
#include <setjmp.h>

void test_TheFirstThingToTest();
void test_TheSecondThingToTest();
#endif

